# 1.1 Python Basics

# Your First Python Code

Instructions

*   Hit the run code button to see the output of print(5 / 8)




In [2]:
# Example, do not modify!
print(5 / 8)

# Print the sum of 7 and 10
print (7 + 10)


0.625
17


# Python as a calculator

Instructions


*   Print the result of subtracting **5** from **5** under # Subtraction using print()
*   Print the result of multiplying **3** by **5** under # Multiplication



In [3]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

# How much is your $100 worth after 7 years?
print(100* (1.1**7))

print(2 ** 5)


10
0
15
5.0
4
16
194.87171000000012
32


# Variable Assignment

Instruction

*   Create a variable savings with the value of 100.
*   Check out this variable by typing print(savings) in the script




In [4]:
# Create a variable savings
savings = 100

# Print out savings
print(savings)


100


# Calculations with variables

Instruction

*  Create a variable monthly_savings, equal to 10 and num_months, equal to 4
*  Multiply monthly_savings by num_months and assign it to new_savings
* Print the value of new_savings

In [5]:
# Create a variable savings
monthly_savings = 10

# Create a variable growth_multiplier
num_months = 4

# Calculate result
new_savings = monthly_savings * num_months

# Print out result
print(new_savings)


40


# Other variable types

Instructions

* Create a new float, half, with the value 0.5.
* Create a new string, intro, with the value "Hello! How are you?".
* Create a new boolean, is_good, with the value True



In [7]:
# Create a variable desc
half = 0.5
intro = "Hello! How are you?"
is_good = True


# Operations with other types

Instructions
* Add savings and **new_savings** and assign it to **total_savings**.
* Use **type()** to print the resulting type of total_savings.


* Calculate the sum of intro and intro and assign the result to **doubleintro**.
* Print out doubleintro. Did you expect this?

In [8]:
savings = 100
new_savings = 40

# Calculate total_savings using savings and new_savings
total_savings = savings + new_savings
print(total_savings)

# Print the type of total_savings
print(type(total_savings))

140
<class 'int'>


In [9]:
intro = "Hello! How are you?"

# Assign sum of intro and intro to doubleintro
doubleintro = intro + intro

# Print out doubleintro
print(doubleintro )

Hello! How are you?Hello! How are you?


# 1.2 Python Lists

# Create a List

Instructions                                                         
* Create a list, areas, that contains the area of the hallway (hall), kitchen (kit), living room (liv), bedroom (bed) and bathroom (bath), in this order. Use the predefined variables.
* Print areas with the print() function

In [11]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]

# Print areas
print(areas)


[11.25, 18.0, 20.0, 10.75, 9.5]


# Create lists with different types

Instructions                                                              
* Finish the code that creates the areas list. Build the list so that the list first contains the name of each room as a string and then its area.

* In other words, add the strings "***hallway***", "***kitchen***" and "***bedroom***" at the appropriate locations.                                                
* Print areas again; is the printout more informative this time?

In [1]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway",hall,"kitchen", kit, "living room", liv,"bedroom", bed, "bathroom", bath]

# Print areas
print(areas)


['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


# List of lists

Instructions

* Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
*Print out house; does this way of structuring your data make more sense?

In [1]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]
         ]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


# Subset and conquer

Instructions

* Print out the second element from the areas list (it has the value 11.25).
* Subset and print out the last element of areas, being 9.50. Using a negative index makes sense here!
* Select the number representing the area of the living room (20.0) and print it out.

In [2]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

11.25


In [3]:
# Print out last element from areas
print(areas[-1])

9.5


In [4]:
# Print out the area of the living room
print(areas[5])

20.0


# Slicing and dicing

Instructions                                                                                                                                                                                                                  

*   Use slicing to create a list, downstairs, that contains the first 6 elements of areas.   
                                                       
* Create upstairs, as the last 4 elements of areas. This time, simplify the slicing by omitting the end index.                                                                      
* Print both downstairs and upstairs using print().

In [5]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:10]

# Print out downstairs and upstairs
print(downstairs)
print (upstairs)


['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


# Subsetting lists of lists


Instructions


* Subset the house list to get the float 9.5

In [1]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Subset the house list
house[-1][1]

9.5

# Replace list elements

Instructions                                                                                                                                                                                                         

*   Update the area of the bathroom to be **10.50** square meters instead of **9.50** using negative indexing.


* Make the areas list more trendy! Change "**living room**" to "**chill zone**". Don't use negative indexing this time.

In [2]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [3]:
# Change "living room" to "chill zone"
areas[4] = "chill zone"
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


# Extend a list

Instructions

*   Use the + operator to paste the list **["poolhouse", 24.5]** to the end of the **areas** list. Store the resulting list as ***areas_1***


*   Further extend ***areas_1*** by adding data on your **garage**. Add the string "garage" and float ***15.45***. Name the resulting list ***areas_2***





In [4]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

In [5]:
# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage",15.45]
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


# Delete list elements

Instructions

* Delete the string and float for the "***poolhouse***" from your areas list.
* Print the updated ***areas*** list.

In [1]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Delete the poolhouse items from the list
del areas[10]
del areas[10]

# Print the updated list
print(areas)


['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


# Inner workings of lists

Instructions



*   Change the second command, that creates the variable **areas_copy**, such that **areas_copy** is an explicit copy of areas.                     
* After your edit, changes made to **areas_copy** shouldn't affect areas
 * Submit the answer to check this
   





In [2]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)




[11.25, 18.0, 20.0, 10.75, 9.5]


# 1.3 Function and Packages

# Familiar functions


Instructions

* Use ***print()*** in combination with ***type()*** to print out the type of var1.
* Use len() to get the length of the list **var1**. Wrap it in a **print()** call to directly print it out.
* Use **int()** to convert **var2** to an integer. Store the output as out2

In [3]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

<class 'list'>


In [4]:
# Print out length of var1
print(len(var1))

4


In [5]:
# Convert var2 to an integer: out2
out2 = int(var2)
print(out2)


1


# Multiple Arguments

# Instructios


*   Use **+** to merge the contents of first and second into a new list: ***full***
* Call **sorted()** and on full and specify the reverse argument to be *True*. Save the sorted list as **full_sorted**
*   Finish off by printing out **full_sorted**





In [6]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second
print(full)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [9]:
# Sort full in ascending order: sorted_asc
sorted_asc = sorted(full)
print(sorted_asc)

[9.5, 10.75, 11.25, 18.0, 20.0]


In [10]:
# Sort full in descending order: full_sorted
full_sorted = sorted(full,reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


# String Methods

Instructions

*   Use the **.upper()** method on place and store the result in *place_up*.                                                                   
* Use the syntax for calling methods that you learned in the previous video.
* Print out place and place_up. Did both change?
* Print out the number of o's on the variable place by calling **.count()** on place and passing the letter 'o' as an input to the method                                                                                                                                          
*   We're talking about the variable place, not the word "place"!


In [11]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

In [12]:
# Print out place and place_up
print(place)
print(place_up)

poolhouse
POOLHOUSE


In [13]:
# Print out the number of o's in place
print(place.count('o'))


3


# List Methods

Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:

* .index(): to get the index of the first element of a list that matches  its input and
* .count() : to get the number of times an element appears in a      list.                                                                      
You'll be working on the list with the area of different parts of a house: areas.

Instructions                                                                  

*  Use the **.index()** method to get the index of the element in areas that is equal to **20.0**. Print out this index.
*   Call **.count()** on areas to find out how many times **9.50** appears in the list. Again, simply print out this number



In [14]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

2


In [15]:
# Print out how often 9.50 appears in areas
print(areas.count(9.50))



1


# List Methods (2)

Instructions

*   Use **.append()** twice to add the size of the poolhouse and the garage again: **24.5** and **15.45**, respectively. Make sure to add them in this order.

*   Print out **areas**

*   Use the ***.reverse()*** method to reverse the order of the elements in areas.

*   Print out **areas** once more





In [16]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size

areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [17]:
# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)



[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]
